# Generated by Django 2.1.9 on 2019-06-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReactAppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The React App name you want to use.', max_length=32, verbose_name='React App Name')),
                ('slug', models.SlugField(max_length=32)),
                ('js', models.TextField()),
                ('css', models.TextField()),
                ('manifest', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
            ],
        ),
    ]
