# Generated by Django 2.1.9 on 2019-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reacttools', '0004_auto_20190612_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactappsettings',
            name='build_cmd',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
