# Generated by Django 2.1.9 on 2019-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reacttools', '0007_auto_20190612_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactappsettings',
            name='static_path_prefix',
            field=models.CharField(blank=True, help_text='Tells collectreact wether or not to insert an extra directory into the static file path (js/<prefix>/main.chunk.js)', max_length=128),
        ),
    ]
