# Generated by Django 2.1.9 on 2019-06-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reacttools', '0008_reactappsettings_static_path_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactappsettings',
            name='build_dir',
            field=models.CharField(blank=True, help_text='Note: makes the assumption that the build path is at the root of the project (i.e. project_dir/build/).', max_length=128),
        ),
        migrations.AlterField(
            model_name='reactappsettings',
            name='project_dir',
            field=models.CharField(blank=True, help_text='Note: makes the assumption that the build path is at the root of the project (i.e. project_dir/build/).', max_length=128),
        ),
        migrations.AlterField(
            model_name='reactappsettings',
            name='static_path_prefix',
            field=models.CharField(blank=True, help_text='Tells collectreact wether or not to insert an extra directory into the static file path (i.e. js/prefix/main.chunk.js).  Blank is no prefix.', max_length=128),
        ),
    ]
